/**
 * Catálogo demo: mismos campos que el registro de colaborador (formulario en index.html).
 * nombre = nombre del taller; zona = localidad aproximada para el mapa.
 */
(function () {
  function row(o) {
    const slug = String(o.redes || o.nombre || "taller")
      .replace(/^@/, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 22);
    return {
      telefono: "11-4000-2000",
      correo: (slug || "taller") + "@demo.portal",
      redes: "@portalgbn",
      ubicacion: "propia",
      horarios: "Consultar calendario publico del espacio.",
      palabrasClave: "",
      ...o,
    };
  }

  window.WORKSHOP_CATALOG = [
    row({
      nombre: "Taller Melodia Urbana",
      rubro: "Musica",
      zona: "Malvinas",
      estado: "Aprobado",
      colaboradorNombre: "Laura Fernandez",
      telefono: "11-4522-1100",
      correo: "laura.melodia@demo.portal",
      descripcion: "Espacio comunitario para aprender musica popular en grupo, sin necesidad de experiencia previa.",
      actividades: "Guitarra acustica y electrica, canto grupal, ensamble y arreglos sencillos.",
      redes: "@melodiaurbana",
      ubicacion: "propia",
      direccion: "Av. de Mayo 1450, Malvinas",
      horarios: "Lun a Vie 18:00 a 21:00",
      palabrasClave: "musica guitarra canto rock folklore",
    }),
    row({
      nombre: "Centro de danza comunitaria",
      rubro: "Danza",
      zona: "Los Polvorines",
      estado: "Aprobado",
      colaboradorNombre: "Marina Costa",
      telefono: "11-4522-2201",
      correo: "marina.danza@demo.portal",
      descripcion: "Clases abiertas de danza contemporanea y folclore para todas las edades en sede municipal cedida.",
      actividades: "Danza contemporanea, folclore, elongacion y ritmo corporal.",
      redes: "@danzaenbarrio",
      ubicacion: "centro",
      direccion: "Sede cultural Los Polvorines, acceso principal",
      horarios: "Mar y Jue 17:00 a 20:00",
      palabrasClave: "danza baile movimiento cuerpo folclore",
    }),
    row({
      nombre: "Taller de ceramica El Horno",
      rubro: "Arte",
      zona: "Grand Bourg",
      estado: "Aprobado",
      colaboradorNombre: "Esteban Rios",
      telefono: "11-4522-3302",
      correo: "esteban.elhorno@demo.portal",
      descripcion: "Taller de alfareria y esmaltado con horno comunitario; materiales incluidos en la cuota simbolica.",
      actividades: "Modelado en torno, mano, esmaltes y cocciones.",
      redes: "@elhornoceramica",
      ubicacion: "propia",
      direccion: "Pasaje Horno 88, Grand Bourg",
      horarios: "Sab 10:00 a 14:00",
      palabrasClave: "ceramica arcilla arte taller horno",
    }),
    row({
      nombre: "Fotografia en barrio",
      rubro: "Fotografia",
      zona: "Pablo Podesta",
      estado: "Pendiente",
      colaboradorNombre: "Julian Almada",
      telefono: "11-4522-4403",
      correo: "julian.foto@demo.portal",
      descripcion: "Salidas fotograficas urbanas y edicion basica con celular y camara reflex.",
      actividades: "Encuadre, luz natural, revelado digital, narrativa en imagenes.",
      redes: "@fotobarriook",
      ubicacion: "propia",
      direccion: "Colectora Gral Paz km 23, local 4",
      horarios: "Dom 9:00 a 13:00",
      palabrasClave: "foto camara imagen retrato calle",
    }),
    row({
      nombre: "Teatro del encuentro",
      rubro: "Teatro",
      zona: "Jose C. Paz",
      estado: "Aprobado",
      colaboradorNombre: "Carla Mendez",
      telefono: "11-4522-5504",
      correo: "carla.teatro@demo.portal",
      descripcion: "Laboratorio de actuacion y dramaturgia vecinal para montajes cortos en espacios publicos.",
      actividades: "Voz, improvisacion, lectura de textos y puesta en escena.",
      redes: "@teatroencuentro",
      ubicacion: "centro",
      direccion: "Centro vecinal Jose C. Paz, sala 2",
      horarios: "Mie 19:00 a 22:00",
      palabrasClave: "teatro actuacion escena obra",
    }),
    row({
      nombre: "Informatica para adultos mayores",
      rubro: "Tecnologia",
      zona: "San Miguel",
      estado: "Aprobado",
      colaboradorNombre: "Roberto Vega",
      telefono: "11-4522-6605",
      correo: "roberto.digital@demo.portal",
      descripcion: "Acompanamiento en uso de celular, correo y tramites en linea con ritmo pausado.",
      actividades: "Android, WhatsApp, Mi Argentina, videollamadas y seguridad basica.",
      redes: "@digitalmayores",
      ubicacion: "centro",
      direccion: "Biblioteca popular San Miguel",
      horarios: "Lun y Vie 10:00 a 12:00",
      palabrasClave: "informatica computadora celular internet curso",
    }),
    row({
      nombre: "Yoga matutino en el parque",
      rubro: "Bienestar",
      zona: "Del Viso",
      estado: "Aprobado",
      colaboradorNombre: "Paula Soria",
      telefono: "11-4522-7706",
      correo: "paula.yoga@demo.portal",
      descripcion: "Practica de yoga suave al aire libre; se lleva mat o mantas comunitarias.",
      actividades: "Hatha yoga, respiracion, relajacion guiada.",
      redes: "@yogaparquegba",
      ubicacion: "centro",
      direccion: "Parque lineal Del Viso, ingreso norte",
      horarios: "Mar y Jue 8:00 a 9:00",
      palabrasClave: "yoga bienestar estiramiento meditacion",
    }),
    row({
      nombre: "Panaderia artesanal",
      rubro: "Gastronomia",
      zona: "Tortuguitas",
      estado: "Pendiente",
      colaboradorNombre: "Hugo Benitez",
      telefono: "11-4522-8807",
      correo: "hugo.pan@demo.portal",
      descripcion: "Taller de masas madre, panes de campo y facturas con ingredientes locales.",
      actividades: "Amasijo, horno de barro, fermentacion lenta, degustacion.",
      redes: "@panvecinal",
      ubicacion: "propia",
      direccion: "Ruta 9 y colectora, galpon 3",
      horarios: "Sab 15:00 a 19:00",
      palabrasClave: "pan comida cocina horno gastronomia restaurante desayuno",
    }),
    row({
      nombre: "Lengua de senas argentina (LSA)",
      rubro: "Inclusion",
      zona: "Malvinas",
      estado: "Aprobado",
      colaboradorNombre: "Nadia Romero",
      telefono: "11-4522-9908",
      correo: "nadia.lsa@demo.portal",
      descripcion: "Curso inicial de LSA con enfoque en encuentros comunitarios y accesibilidad.",
      actividades: "Vocabulario basico, conversacion, cultura sorda.",
      redes: "@lsamalvinas",
      ubicacion: "centro",
      direccion: "Escuela 12, anexo inclusivo",
      horarios: "Jue 18:00 a 20:00",
      palabrasClave: "lsa senas inclusion accesibilidad",
    }),
    row({
      nombre: "Escritura creativa",
      rubro: "Literatura",
      zona: "Los Polvorines",
      estado: "Aprobado",
      colaboradorNombre: "Ivan Krause",
      telefono: "11-4523-0010",
      correo: "ivan.escribe@demo.portal",
      descripcion: "Taller literario para cuentos breves y poesia con lectura en voz alta mensual.",
      actividades: "Ejercicios de escritura, revision en grupo, antologia vecinal.",
      redes: "@escrituravecinal",
      ubicacion: "propia",
      direccion: "Calle Sarmiento 2100, Los Polvorines",
      horarios: "Mie 19:30 a 21:30",
      palabrasClave: "literatura cuento poesia lectura libro",
    }),
    row({
      nombre: "Jardineria y huerta urbana",
      rubro: "Ecologia",
      zona: "Grand Bourg",
      estado: "Aprobado",
      colaboradorNombre: "Lucia Peralta",
      telefono: "11-4523-1120",
      correo: "lucia.huerta@demo.portal",
      descripcion: "Montaje de canteros y compostaje en espacios comunitarios con riego por goteo casero.",
      actividades: "Siembra, poda, control de plagas ecologico, semillas nativas.",
      redes: "@huertagba",
      ubicacion: "centro",
      direccion: "Huerta comunitaria Grand Bourg",
      horarios: "Sab 9:00 a 12:00",
      palabrasClave: "jardin plantas huerta compost ecologia",
    }),
    row({
      nombre: "Bordado y textil",
      rubro: "Manualidades",
      zona: "Pablo Podesta",
      estado: "Aprobado",
      colaboradorNombre: "Marta Ibanez",
      telefono: "11-4523-2230",
      correo: "marta.bordado@demo.portal",
      descripcion: "Tecnicas de bordado tradicional y aplicaciones en indumentaria recuperada.",
      actividades: "Punto cruz, bastidor, hilos y telas recicladas.",
      redes: "@textilvecinal",
      ubicacion: "propia",
      direccion: "Av. San Martin 3400",
      horarios: "Mar 16:00 a 19:00",
      palabrasClave: "bordado textil costura manualidades hilo",
    }),
    row({
      nombre: "Repaso de matematica secundaria",
      rubro: "Educacion",
      zona: "Jose C. Paz",
      estado: "Pendiente",
      colaboradorNombre: "Diego Coronel",
      telefono: "11-4523-3340",
      correo: "diego.mates@demo.portal",
      descripcion: "Apoyo escolar en algebra y geometria con material gratuito y ejercicios resueltos en grupo.",
      actividades: "Funciones, proporciones, estadistica basica, preparacion pruebas.",
      redes: "@matesjcp",
      ubicacion: "centro",
      direccion: "Biblioteca Jose C. Paz, sala estudiantes",
      horarios: "Lun a Vie 15:00 a 18:00",
      palabrasClave: "matematica escuela secundaria apoyo estudio",
    }),
    row({
      nombre: "Serigrafia y estampado",
      rubro: "Diseno",
      zona: "San Miguel",
      estado: "Aprobado",
      colaboradorNombre: "Florencia Paz",
      telefono: "11-4523-4450",
      correo: "flor.serigrafia@demo.portal",
      descripcion: "Produccion de remeras y tote bags con mensajes de campanas vecinales.",
      actividades: "Mascaras, tintas al agua, mesa de estampado.",
      redes: "@estampaok",
      ubicacion: "propia",
      direccion: "Cochabamba 780, San Miguel",
      horarios: "Vie 14:00 a 19:00",
      palabrasClave: "serigrafia estampado diseno remera",
    }),
    row({
      nombre: "Ajedrez para principiantes",
      rubro: "Juegos",
      zona: "Del Viso",
      estado: "Aprobado",
      colaboradorNombre: "Alberto Nunez",
      telefono: "11-4523-5560",
      correo: "alberto.ajedrez@demo.portal",
      descripcion: "Club escolar de ajedrez con torneos internos y charlas de aperturas.",
      actividades: "Reglas, tacticas, partidas blitz, analisis en grupo.",
      redes: "@ajedrezdelviso",
      ubicacion: "centro",
      direccion: "Polideportivo Del Viso",
      horarios: "Sab 11:00 a 13:00",
      palabrasClave: "ajedrez juego estrategia torneo",
    }),
    row({
      nombre: "Violin y ensamble infantil",
      rubro: "Musica",
      zona: "Tortuguitas",
      estado: "Aprobado",
      colaboradorNombre: "Camila Duarte",
      telefono: "11-4523-6670",
      correo: "camila.violin@demo.portal",
      descripcion: "Iniciacion al violin en grupos chicos con instrumentos cedidos por la cooperadora.",
      actividades: "Postura, digitacion, lectura simple, ensamble de cuerdas.",
      redes: "@violinespacio",
      ubicacion: "centro",
      direccion: "Escuela primaria 45, anexo musica",
      horarios: "Mie y Vie 16:00 a 17:30",
      palabrasClave: "violin musica instrumento ninos orquesta",
    }),
    row({
      nombre: "Nutricion y taller de cocina saludable",
      rubro: "Salud",
      zona: "Malvinas",
      estado: "Aprobado",
      colaboradorNombre: "Veronica Salas",
      telefono: "11-4523-7780",
      correo: "vero.nutricion@demo.portal",
      descripcion: "Charlas de plato saludable con degustacion y etiquetado de alimentos.",
      actividades: "Menu semanal, recetas bajas en sodio, taller de snacks.",
      redes: "@cocinasaludablegba",
      ubicacion: "centro",
      direccion: "CAPS Malvinas, sala multifuncion",
      horarios: "Jue 10:00 a 12:00",
      palabrasClave: "nutricion salud cocina comida alimentacion restaurante casero",
    }),
    row({
      nombre: "Origami y papel reciclado",
      rubro: "Manualidades",
      zona: "Los Polvorines",
      estado: "Pendiente",
      colaboradorNombre: "Sofia Linares",
      telefono: "11-4523-8890",
      correo: "sofia.origami@demo.portal",
      descripcion: "Figuras de papel con hojas reutilizadas de impresion y diarios comunitarios.",
      actividades: "Plegado modular, cajas regalo, moviles decorativos.",
      redes: "@origamigba",
      ubicacion: "propia",
      direccion: "Calle Fournier 560",
      horarios: "Dom 16:00 a 18:00",
      palabrasClave: "origami papel manualidades reciclaje",
    }),
    row({
      nombre: "Historia local del partido",
      rubro: "Historia",
      zona: "Grand Bourg",
      estado: "Aprobado",
      colaboradorNombre: "Hector Maidana",
      telefono: "11-4523-9900",
      correo: "hector.historia@demo.portal",
      descripcion: "Archivo oral con vecinos y recorridos por hitos del crecimiento urbano.",
      actividades: "Entrevistas, mapas historicos, exposicion final.",
      redes: "@historialocalgba",
      ubicacion: "centro",
      direccion: "Museo barrial Grand Bourg",
      horarios: "Sab 18:00 a 20:00",
      palabrasClave: "historia memoria archivo barrio",
    }),
    row({
      nombre: "Guitarra electrica nivel 1",
      rubro: "Musica",
      zona: "Pablo Podesta",
      estado: "Aprobado",
      colaboradorNombre: "Leo Santillan",
      telefono: "11-4524-1010",
      correo: "leo.guitarra@demo.portal",
      descripcion: "Rock y blues con amplificacion comunitaria; se prioriza seguridad auditiva.",
      actividades: "Acordes power, ritmo, improvisacion corta, ensayo en grupo.",
      redes: "@guitarraelecgba",
      ubicacion: "propia",
      direccion: "Taller sonoro Pablo Podesta, galpon 7",
      horarios: "Mar y Jue 20:00 a 22:00",
      palabrasClave: "guitarra electrica musica rock amplificador",
    }),
    row({
      nombre: "Zumba vecinal",
      rubro: "Danza",
      zona: "Jose C. Paz",
      estado: "Aprobado",
      colaboradorNombre: "Yanina Morales",
      telefono: "11-4524-2120",
      correo: "yanina.zumba@demo.portal",
      descripcion: "Fitness latino en plaza con musica moderada y coreografias simples.",
      actividades: "Calentamiento, coreo merengue y reggaeton, vuelta a la calma.",
      redes: "@zumbajcp",
      ubicacion: "centro",
      direccion: "Plaza central Jose C. Paz",
      horarios: "Lun y Mie 19:00 a 20:00",
      palabrasClave: "zumba danza fitness baile latino",
    }),
    row({
      nombre: "Quimica divertida (secundaria)",
      rubro: "Ciencia",
      zona: "San Miguel",
      estado: "Pendiente",
      colaboradorNombre: "Gustavo Prieto",
      telefono: "11-4524-3230",
      correo: "gustavo.quimica@demo.portal",
      descripcion: "Experimentos seguros con materiales de cocina y explicacion del metodo cientifico.",
      actividades: "PH, reacciones suaves, cristalizacion, juego de mesa cientifico.",
      redes: "@quimicadivertida",
      ubicacion: "centro",
      direccion: "Club de ciencias San Miguel",
      horarios: "Sab 10:00 a 12:00",
      palabrasClave: "quimica ciencia experimento escuela",
    }),
    row({
      nombre: "Karate infantil",
      rubro: "Deporte",
      zona: "Del Viso",
      estado: "Aprobado",
      colaboradorNombre: "Kenji Okamoto",
      telefono: "11-4524-4340",
      correo: "kenji.karate@demo.portal",
      descripcion: "Karate recreativo con valores de respeto y control de cuerpo.",
      actividades: "Kihon, kata basico, juego motor, cinturon blanco.",
      redes: "@karatedelviso",
      ubicacion: "centro",
      direccion: "Gimnasio municipal Del Viso",
      horarios: "Mar y Jue 17:00 a 18:00",
      palabrasClave: "karate deporte artes marciales ninos",
    }),
    row({
      nombre: "Ukelele en grupo",
      rubro: "Musica",
      zona: "Tortuguitas",
      estado: "Aprobado",
      colaboradorNombre: "Agustina Rey",
      telefono: "11-4524-5450",
      correo: "agus.uke@demo.portal",
      descripcion: "Taller de musica con ukelele para cantar canciones en grupo; instrumentos en prestamo.",
      actividades: "Acordes basicos, rasgueo, cancionero popular, ukulele ukelele.",
      redes: "@ukegrupo",
      ubicacion: "propia",
      direccion: "Barrio San Jorge, Tortuguitas, casa club",
      horarios: "Vie 18:00 a 20:00",
      palabrasClave: "ukelele ukulele musica canto acordes taller de musica",
    }),
    row({
      nombre: "Web para emprendedores",
      rubro: "Tecnologia",
      zona: "Malvinas",
      estado: "Aprobado",
      colaboradorNombre: "Nicolas Ferreyra",
      telefono: "11-4524-6560",
      correo: "nico.web@demo.portal",
      descripcion: "Pagina simple con catologo de productos y formulario de pedidos para ferias.",
      actividades: "HTML basico, hosting gratuito, redes vinculadas, accesibilidad minima.",
      redes: "@webvecinal",
      ubicacion: "propia",
      direccion: "Coworking Malvinas, piso 2",
      horarios: "Sab 10:00 a 13:00",
      palabrasClave: "web internet pagina emprendedor tecnologia",
    }),
    row({
      nombre: "Expresion plastica ninos",
      rubro: "Arte",
      zona: "Los Polvorines",
      estado: "Aprobado",
      colaboradorNombre: "Romina Sosa",
      telefono: "11-4524-7670",
      correo: "roma.plastica@demo.portal",
      descripcion: "Pintura y collage con materiales no toxicos para infancias de 5 a 10 anos.",
      actividades: "Temperas, papel recortado, trabajo sobre mural colectivo.",
      redes: "@plasticakids",
      ubicacion: "centro",
      direccion: "Jardin comunitario Los Polvorines",
      horarios: "Mie 16:00 a 17:30",
      palabrasClave: "arte pintura ninos plastico color",
    }),
    row({
      nombre: "Risoterapia y relajacion",
      rubro: "Bienestar",
      zona: "Grand Bourg",
      estado: "Pendiente",
      colaboradorNombre: "Elena Brusa",
      telefono: "11-4524-8780",
      correo: "elena.riso@demo.portal",
      descripcion: "Dinamicas de risa guiada y relajacion para adultos mayores y cuidadores.",
      actividades: "Ejercicios respiracion, juegos sin competencia, cierre mindfulness.",
      redes: "@risoterapiagba",
      ubicacion: "centro",
      direccion: "Centro de dia Grand Bourg",
      horarios: "Jue 11:00 a 12:30",
      palabrasClave: "risoterapia bienestar risa relajacion salud emocional",
    }),
    row({
      nombre: "Marroquineria basica",
      rubro: "Artesania",
      zona: "Pablo Podesta",
      estado: "Aprobado",
      colaboradorNombre: "Federico Lema",
      telefono: "11-4524-9890",
      correo: "fede.cuero@demo.portal",
      descripcion: "Corte y cosido de cuero vegetal para billeteras y porta tarjetas.",
      actividades: "Patrones, punzon, hilo encerado, acabados.",
      redes: "@cuerogba",
      ubicacion: "propia",
      direccion: "Taller cuero Pablo Podesta, local 2",
      horarios: "Sab 14:00 a 18:00",
      palabrasClave: "cuero marroquineria artesania cartera",
    }),
    row({
      nombre: "Salsa y bachata social",
      rubro: "Danza",
      zona: "Jose C. Paz",
      estado: "Aprobado",
      colaboradorNombre: "Dario y Mica",
      telefono: "11-4525-0901",
      correo: "dario.salsa@demo.portal",
      descripcion: "Parejas y solteros: pasos base de salsa cubana y bachata sensual moderada.",
      actividades: "Figuras sociales, musicalidad, pista y etiqueta.",
      redes: "@salsasocialjcp",
      ubicacion: "centro",
      direccion: "Salon cultural Jose C. Paz",
      horarios: "Vie 21:00 a 23:00",
      palabrasClave: "salsa bachata danza baile social",
    }),
    row({
      nombre: "Corte y confeccion nivel inicial",
      rubro: "Textil",
      zona: "San Miguel",
      estado: "Aprobado",
      colaboradorNombre: "Graciela Ortiz",
      telefono: "11-4525-1012",
      correo: "graciela.textil@demo.portal",
      descripcion: "Uso de maquina familiar y armado de prendas basicas con molde comun.",
      actividades: "Tijera, maquina recta, costuras rectas y curvas, terminaciones.",
      redes: "@confeccionvecinal",
      ubicacion: "propia",
      direccion: "Taller textil San Miguel, pasillo 5",
      horarios: "Mar y Jue 14:00 a 17:00",
      palabrasClave: "costura confeccion textil maquina modista",
    }),
    row({
      nombre: "Pintura al oleo",
      rubro: "Arte",
      zona: "Del Viso",
      estado: "Aprobado",
      colaboradorNombre: "Andrea Ponce",
      telefono: "11-4525-2123",
      correo: "andrea.oleo@demo.portal",
      descripcion: "Paisajes y naturalezas muertas con oleos al agua y solventes controlados.",
      actividades: "Mezcla de color, pincelada, bastidor, secado.",
      redes: "@oleogba",
      ubicacion: "propia",
      direccion: "Atelier Del Viso, 1er piso",
      horarios: "Dom 17:00 a 20:00",
      palabrasClave: "pintura oleo arte lienzo color",
    }),
    row({
      nombre: "Electricidad domiciliaria basica",
      rubro: "Oficios",
      zona: "Tortuguitas",
      estado: "Pendiente",
      colaboradorNombre: "Miguel Arce",
      telefono: "11-4525-3234",
      correo: "miguel.electricidad@demo.portal",
      descripcion: "Mediciones con tester, cambio de interruptores y normas de seguridad en hogar.",
      actividades: "Cableado simple, tablero, proteccion personal, no habilita matricula.",
      redes: "@electricidadsegura",
      ubicacion: "propia",
      direccion: "Taller oficios Tortuguitas",
      horarios: "Sab 9:00 a 12:00",
      palabrasClave: "electricidad oficio casa instalacion luz",
    }),
    row({
      nombre: "First aid y RCP vecinal",
      rubro: "Salud",
      zona: "Malvinas",
      estado: "Aprobado",
      colaboradorNombre: "Patricio Lozano",
      telefono: "11-4525-4345",
      correo: "patricio.primerosaux@demo.portal",
      descripcion: "Primeros auxilios y RCP con maniqui; certificado de asistencia no oficial.",
      actividades: "ABC, hemorragias, RCP adulto y nino, desfibrilador intro.",
      redes: "@rcpvecinal",
      ubicacion: "centro",
      direccion: "Bomberos voluntarios Malvinas, aula",
      horarios: "Dom 10:00 a 13:00",
      palabrasClave: "primeros auxilios rcp salud emergencia rescate",
    }),
    row({
      nombre: "Dibujo anatomico",
      rubro: "Arte",
      zona: "Los Polvorines",
      estado: "Aprobado",
      colaboradorNombre: "Valeria Quinteros",
      telefono: "11-4525-5456",
      correo: "vale.anatomia@demo.portal",
      descripcion: "Proporcion humana con modelo esqueletico y croquis rapidos.",
      actividades: "Estructura osea, musculos superficie, sombreado lapiz.",
      redes: "@dibujocuerpo",
      ubicacion: "centro",
      direccion: "Escuela de arte Los Polvorines",
      horarios: "Mie 18:00 a 20:30",
      palabrasClave: "dibujo anatomia arte lapiz cuerpo",
    }),
    row({
      nombre: "Lectura y club de cuentos",
      rubro: "Literatura",
      zona: "Grand Bourg",
      estado: "Aprobado",
      colaboradorNombre: "Cecilia Amarilla",
      telefono: "11-4525-6567",
      correo: "ceci.cuentos@demo.portal",
      descripcion: "Lectura en voz alta y debate para familias con ninos de primaria.",
      actividades: "Cuentos latinoamericanos, dramatizacion leve, biblioteca ambulante.",
      redes: "@clubcuentosgba",
      ubicacion: "centro",
      direccion: "Biblioteca Grand Bourg",
      horarios: "Sab 11:00 a 12:30",
      palabrasClave: "lectura cuentos libro ninos familia",
    }),
    row({
      nombre: "Tango milonguero",
      rubro: "Danza",
      zona: "Pablo Podesta",
      estado: "Aprobado",
      colaboradorNombre: "Oscar y Nora",
      telefono: "11-4525-7678",
      correo: "oscar.tango@demo.portal",
      descripcion: "Abrazo, caminata y musicalidad de orquestas clasicas en espacio sin competencia.",
      actividades: "Tecnica de abrazo, cadencias, cortes y quebradas suaves.",
      redes: "@tangomilonga",
      ubicacion: "centro",
      direccion: "Centro cultural Pablo Podesta",
      horarios: "Sab 20:30 a 23:00",
      palabrasClave: "tango danza milonga baile abrazo",
    }),
    row({
      nombre: "Bateria y ritmo",
      rubro: "Musica",
      zona: "Jose C. Paz",
      estado: "Pendiente",
      colaboradorNombre: "Bruno Callieri",
      telefono: "11-4525-8789",
      correo: "bruno.bateria@demo.portal",
      descripcion: "Ritmos de rock y candombe con pad practice y set comunitario acolchado.",
      actividades: "Rudimentos, coordinacion mano-pie, ensamble con base grabada.",
      redes: "@bateriajcp",
      ubicacion: "propia",
      direccion: "Sotano sonido Jose C. Paz",
      horarios: "Jue 19:00 a 21:00",
      palabrasClave: "bateria musica ritmo percusion rock",
    }),
    row({
      nombre: "Costura y arreglos express",
      rubro: "Textil",
      zona: "San Miguel",
      estado: "Aprobado",
      colaboradorNombre: "Ines Molina",
      telefono: "11-4525-9890",
      correo: "ines.costura@demo.portal",
      descripcion: "Arreglos de prendas en el dia: bajos, cierres y parches decorativos.",
      actividades: "Maquina overlock, puntada a mano, elasticos.",
      redes: "@arreglosrapidos",
      ubicacion: "propia",
      direccion: "Puesto feria San Miguel, pasillo textil",
      horarios: "Sab 9:00 a 14:00",
      palabrasClave: "costura textil arreglos modista ropa",
    }),
  ];
})();
